airiot:
  driver:
    id: java-sdk-demo
    name: java-sdk-demo
    project-id: 647d3f6db395ea47865d4b9e
    instance-id: JavaSdkDemo
mq:
  mqtt:
    host: airiot.link
    port: 55883
    username: admin
    password: public
driver-grpc:
  host: airiot.link
  port: 55224