airiot:
  driver:
    id: mqtt-driver-demo
    name: mqtt-driver-demo
    project-id: 647d3f6db395ea47865d4b9e
    instance-id: JavaSdkDemo
mq:
  mqtt:
    host: 121.89.244.23
    port: 1883
    username: admin
    password: public
driver-grpc:
  host: 121.89.244.23
  port: 9224